# Indicators

In [5]:
import pandas as pd
import talib as ta
import numpy as np

In [2]:
btc_yahoo = pd.read_csv('/home/giujorge/datalake/lab/Crypto/crypto/data/external/yahoo/daily/usd/BTC-USD.csv', parse_dates=True, index_col=0)
btc_yahoo.head()

Open        High         Low       Close   Adj Close  \
Date                                                                     
2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   
2014-09-20  394.673004  423.295990  389.882996  408.903992  408.903992   
2014-09-21  408.084991  412.425995  393.181000  398.821014  398.821014   

                Volume  
Date                    
2014-09-17  21056800.0  
2014-09-18  34483200.0  
2014-09-19  37919700.0  
2014-09-20  36863600.0  
2014-09-21  26580100.0

In [ ]:
'CDL2CROWS','CDL3BLACKCROWS','CDL3INSIDE','CDL3LINESTRIKE','CDL3OUTSIDE','CDL3STARSINSOUTH','CDL3WHITESOLDIERS','CDLABANDONEDBABY','CDLADVANCEBLOCK','CDLBELTHOLD','CDLBREAKAWAY','CDLCLOSINGMARUBOZU','CDLCONCEALBABYSWALL','CDLCOUNTERATTACK','CDLDARKCLOUDCOVER','CDLDOJI','CDLDOJISTAR','CDLDRAGONFLYDOJI','CDLENGULFING','CDLEVENINGDOJISTAR','CDLEVENINGSTAR','CDLGAPSIDESIDEWHITE','CDLGRAVESTONEDOJI','CDLHAMMER','CDLHANGINGMAN','CDLHARAMI','CDLHARAMICROSS','CDLHIGHWAVE','CDLHIKKAKE','CDLHIKKAKEMOD','CDLHOMINGPIGEON','CDLIDENTICAL3CROWS','CDLINNECK','CDLINVERTEDHAMMER','CDLKICKING','CDLKICKINGBYLENGTH','CDLLADDERBOTTOM','CDLLONGLEGGEDDOJI','CDLLONGLINE','CDLMARUBOZU','CDLMATCHINGLOW','CDLMATHOLD','CDLMORNINGDOJISTAR','CDLMORNINGSTAR','CDLONNECK','CDLPIERCING','CDLRICKSHAWMAN','CDLRISEFALL3METHODS','CDLSEPARATINGLINES','CDLSHOOTINGSTAR','CDLSHORTLINE','CDLSPINNINGTOP','CDLSTALLEDPATTERN','CDLSTICKSANDWICH','CDLTAKURI','CDLTASUKIGAP','CDLTHRUSTING','CDLTRISTAR','CDLUNIQUE3RIVER','CDLUPSIDEGAP2CROWS','CDLXSIDEGAP3METHODS'

In [7]:
btc_array = btc_yahoo.to_numpy()

In [10]:
btc_array

array([[4.65864014e+02, 4.68174011e+02, 4.52421997e+02, 4.57334015e+02,
        4.57334015e+02, 2.10568000e+07],
       [4.56859985e+02, 4.56859985e+02, 4.13104004e+02, 4.24440002e+02,
        4.24440002e+02, 3.44832000e+07],
       [4.24102997e+02, 4.27834991e+02, 3.84532013e+02, 3.94795990e+02,
        3.94795990e+02, 3.79197000e+07],
       ...,
       [4.92882500e+04, 5.09822734e+04, 4.83860859e+04, 5.00253750e+04,
        5.00253750e+04, 4.32061796e+10],
       [5.00093242e+04, 5.05455820e+04, 4.95487812e+04, 4.99446250e+04,
        4.99446250e+04, 3.74713278e+10],
       [4.99672578e+04, 5.03807344e+04, 4.95486719e+04, 5.03807344e+04,
        5.03807344e+04, 3.08656579e+10]])

In [12]:
btc_array[:,0]

array([  465.864014,   456.859985,   424.102997, ..., 49288.25    ,
       50009.324219, 49967.257813])

In [13]:
ta.CDL2CROWS(btc_array[:,0], btc_array[:,1], btc_array[:,2], btc_array[:,4])

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [14]:
## CDL2CROWS - Two Crows

btc_yahoo['CDL2CROWS'] = ta.CDL2CROWS(btc_array[:,0], btc_array[:,1], btc_array[:,2], btc_array[:,4])

In [25]:
btc_yahoo.shape

(2546, 7)

In [24]:
btc_yahoo[btc_yahoo['CDL2CROWS'] == 0]

Open          High           Low         Close  \
Date                                                                 
2014-09-17    465.864014    468.174011    452.421997    457.334015   
2014-09-18    456.859985    456.859985    413.104004    424.440002   
2014-09-19    424.102997    427.834991    384.532013    394.795990   
2014-09-20    394.673004    423.295990    389.882996    408.903992   
2014-09-21    408.084991    412.425995    393.181000    398.821014   
...                  ...           ...           ...           ...   
2021-09-01  47099.773438  49111.089844  46562.437500  48847.027344   
2021-09-02  48807.847656  50343.421875  48652.320313  49327.722656   
2021-09-03  49288.250000  50982.273438  48386.085938  50025.375000   
2021-09-04  50009.324219  50545.582031  49548.781250  49944.625000   
2021-09-05  49967.257813  50380.734375  49548.671875  50380.734375   

               Adj Close        Volume  CDL2CROWS  
Date                                               
2014-09-17    457.334015  2.105680e+07          0  
2014-09-18    424.440002  3.448320e+07          0  
2014-09-19    394.795990  3.791970e+07          0  
2014-09-20    408.903992  3.686360e+07          0  
2014-09-21    398.821014  2.658010e+07          0  
...                  ...           ...        ...  
2021-09-01  48847.027344  3.913940e+10          0  
2021-09-02  49327.722656  3.950807e+10          0  
2021-09-03  50025.375000  4.320618e+10          0  
2021-09-04  49944.625000  3.747133e+10          0  
2021-09-05  50380.734375  3.086566e+10          0  

[2546 rows x 7 columns]

In [ ]:


CDL3BLACKCROWS - Three Black Crows

integer = CDL3BLACKCROWS(open, high, low, close)

CDL3INSIDE - Three Inside Up/Down

integer = CDL3INSIDE(open, high, low, close)

CDL3LINESTRIKE - Three-Line Strike

integer = CDL3LINESTRIKE(open, high, low, close)

CDL3OUTSIDE - Three Outside Up/Down

integer = CDL3OUTSIDE(open, high, low, close)

CDL3STARSINSOUTH - Three Stars In The South

integer = CDL3STARSINSOUTH(open, high, low, close)

CDL3WHITESOLDIERS - Three Advancing White Soldiers

integer = CDL3WHITESOLDIERS(open, high, low, close)

CDLABANDONEDBABY - Abandoned Baby

integer = CDLABANDONEDBABY(open, high, low, close, penetration=0)

CDLADVANCEBLOCK - Advance Block

integer = CDLADVANCEBLOCK(open, high, low, close)

CDLBELTHOLD - Belt-hold

integer = CDLBELTHOLD(open, high, low, close)

CDLBREAKAWAY - Breakaway

integer = CDLBREAKAWAY(open, high, low, close)

CDLCLOSINGMARUBOZU - Closing Marubozu

integer = CDLCLOSINGMARUBOZU(open, high, low, close)

CDLCONCEALBABYSWALL - Concealing Baby Swallow

integer = CDLCONCEALBABYSWALL(open, high, low, close)

CDLCOUNTERATTACK - Counterattack

integer = CDLCOUNTERATTACK(open, high, low, close)

CDLDARKCLOUDCOVER - Dark Cloud Cover

integer = CDLDARKCLOUDCOVER(open, high, low, close, penetration=0)

CDLDOJI - Doji

integer = CDLDOJI(open, high, low, close)

CDLDOJISTAR - Doji Star

integer = CDLDOJISTAR(open, high, low, close)

CDLDRAGONFLYDOJI - Dragonfly Doji

integer = CDLDRAGONFLYDOJI(open, high, low, close)

CDLENGULFING - Engulfing Pattern

integer = CDLENGULFING(open, high, low, close)

CDLEVENINGDOJISTAR - Evening Doji Star

integer = CDLEVENINGDOJISTAR(open, high, low, close, penetration=0)

CDLEVENINGSTAR - Evening Star

integer = CDLEVENINGSTAR(open, high, low, close, penetration=0)

CDLGAPSIDESIDEWHITE - Up/Down-gap side-by-side white lines

integer = CDLGAPSIDESIDEWHITE(open, high, low, close)

CDLGRAVESTONEDOJI - Gravestone Doji

integer = CDLGRAVESTONEDOJI(open, high, low, close)

CDLHAMMER - Hammer

integer = CDLHAMMER(open, high, low, close)

CDLHANGINGMAN - Hanging Man

integer = CDLHANGINGMAN(open, high, low, close)

CDLHARAMI - Harami Pattern

integer = CDLHARAMI(open, high, low, close)

CDLHARAMICROSS - Harami Cross Pattern

integer = CDLHARAMICROSS(open, high, low, close)

CDLHIGHWAVE - High-Wave Candle

integer = CDLHIGHWAVE(open, high, low, close)

CDLHIKKAKE - Hikkake Pattern

integer = CDLHIKKAKE(open, high, low, close)

CDLHIKKAKEMOD - Modified Hikkake Pattern

integer = CDLHIKKAKEMOD(open, high, low, close)

CDLHOMINGPIGEON - Homing Pigeon

integer = CDLHOMINGPIGEON(open, high, low, close)

CDLIDENTICAL3CROWS - Identical Three Crows

integer = CDLIDENTICAL3CROWS(open, high, low, close)

CDLINNECK - In-Neck Pattern

integer = CDLINNECK(open, high, low, close)

CDLINVERTEDHAMMER - Inverted Hammer

integer = CDLINVERTEDHAMMER(open, high, low, close)

CDLKICKING - Kicking

integer = CDLKICKING(open, high, low, close)

CDLKICKINGBYLENGTH - Kicking - bull/bear determined by the longer marubozu

integer = CDLKICKINGBYLENGTH(open, high, low, close)

CDLLADDERBOTTOM - Ladder Bottom

integer = CDLLADDERBOTTOM(open, high, low, close)

CDLLONGLEGGEDDOJI - Long Legged Doji

integer = CDLLONGLEGGEDDOJI(open, high, low, close)

CDLLONGLINE - Long Line Candle

integer = CDLLONGLINE(open, high, low, close)

CDLMARUBOZU - Marubozu

integer = CDLMARUBOZU(open, high, low, close)

CDLMATCHINGLOW - Matching Low

integer = CDLMATCHINGLOW(open, high, low, close)

CDLMATHOLD - Mat Hold

integer = CDLMATHOLD(open, high, low, close, penetration=0)

CDLMORNINGDOJISTAR - Morning Doji Star

integer = CDLMORNINGDOJISTAR(open, high, low, close, penetration=0)

CDLMORNINGSTAR - Morning Star

integer = CDLMORNINGSTAR(open, high, low, close, penetration=0)

CDLONNECK - On-Neck Pattern

integer = CDLONNECK(open, high, low, close)

CDLPIERCING - Piercing Pattern

integer = CDLPIERCING(open, high, low, close)

CDLRICKSHAWMAN - Rickshaw Man

integer = CDLRICKSHAWMAN(open, high, low, close)

CDLRISEFALL3METHODS - Rising/Falling Three Methods

integer = CDLRISEFALL3METHODS(open, high, low, close)

CDLSEPARATINGLINES - Separating Lines

integer = CDLSEPARATINGLINES(open, high, low, close)

CDLSHOOTINGSTAR - Shooting Star

integer = CDLSHOOTINGSTAR(open, high, low, close)

CDLSHORTLINE - Short Line Candle

integer = CDLSHORTLINE(open, high, low, close)

CDLSPINNINGTOP - Spinning Top

integer = CDLSPINNINGTOP(open, high, low, close)

CDLSTALLEDPATTERN - Stalled Pattern

integer = CDLSTALLEDPATTERN(open, high, low, close)

CDLSTICKSANDWICH - Stick Sandwich

integer = CDLSTICKSANDWICH(open, high, low, close)

CDLTAKURI - Takuri (Dragonfly Doji with very long lower shadow)

integer = CDLTAKURI(open, high, low, close)

CDLTASUKIGAP - Tasuki Gap

integer = CDLTASUKIGAP(open, high, low, close)

CDLTHRUSTING - Thrusting Pattern

integer = CDLTHRUSTING(open, high, low, close)

CDLTRISTAR - Tristar Pattern

integer = CDLTRISTAR(open, high, low, close)

CDLUNIQUE3RIVER - Unique 3 River

integer = CDLUNIQUE3RIVER(open, high, low, close)

CDLUPSIDEGAP2CROWS - Upside Gap Two Crows

integer = CDLUPSIDEGAP2CROWS(open, high, low, close)

CDLXSIDEGAP3METHODS - Upside/Downside Gap Three Methods

integer = CDLXSIDEGAP3METHODS(open, high, low, close)
